name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Mistral Nemo
    provider: ollama
    model: mistral-nemo:latest
    roles:
      - chat
  - name: Codestral
    provider: ollama
    model: codestral:22b-v0.1-q4_K_M
    roles:
      - chat
  - name: Mistral Small
    provider: ollama
    model: mistral-small:24b
    roles:
      - chat
  - name: Qwen Autocomplete
    provider: ollama
    model: qwen2.5-coder:1.5b
    roles:
      - autocomplete
      - chat
      - apply
